// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6y2qBrXvG3PIj_IbgRWhl36y4ZgNQd8E',
    appId: '1:760544402752:web:32d271c4b8eaec3926aea5',
    messagingSenderId: '760544402752',
    projectId: 'lenden-62884',
    authDomain: 'lenden-62884.firebaseapp.com',
    storageBucket: 'lenden-62884.firebasestorage.app',
    measurementId: 'G-0Y0SMT4PNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbVkAE3g3QMH_Eg78mAwytzL1N-xN-sQ',
    appId: '1:760544402752:android:0f33357a54e259e226aea5',
    messagingSenderId: '760544402752',
    projectId: 'lenden-62884',
    storageBucket: 'lenden-62884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIFJ6q6fCaGv_7nJVarNrTK9H3TuWnh1o',
    appId: '1:760544402752:ios:7f15f9c8f7191a4d26aea5',
    messagingSenderId: '760544402752',
    projectId: 'lenden-62884',
    storageBucket: 'lenden-62884.firebasestorage.app',
    iosBundleId: 'com.example.lenden',
  );
}
